version: "3"
services:
  frontend:
    build: "./frontend"
    depends_on:
      - backend
    ports:
      - "8888:8888"
    networks:
      - back
      - front
  
  backend:
    build: "./backend"
    depends_on:
      - database
    networks:
      - back  

  database:
    image: mysql
    networks:
      - back
    ports:
      - "3306:3306"
    volumes:
      - ./database/names.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    
networks:
  front: 
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
  back: