version: "3"
services:

  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    links: 
     - frontend:frontend
    depends_on:
      - backend
      - frontend
    networks:
      - back
      - front

  frontend:
    build: "./frontend"
    depends_on:
      - backend
    # ports:
    #   - "3000:3000"
    networks:
      # - back
      - front
  
  backend:
    build: "./backend"
    depends_on:
      - database
    networks:
      - back  

  database:
    image: mysql:latest
    networks:
      - back
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    
networks:
  front: 
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
  back: