version: "3"
services:

  # nginx:
  #   build: "./nginx"
  #   ports:
  #     - "80:80"
  #   links: 
  #    - frontend:frontend
  #    - backend:backend
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - back

  frontend:
    build: "./frontend"
    links: 
      - backend:backend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - back
  
  backend:
    build: "./backend"
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - back  

  database:
    image: mysql:latest
    networks:
      - back
    ports:
      - "3306:3306"
    volumes:
      - ./datadb:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    
networks:
  front: 
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
  back: